Details popup window
ibugithub/Portfolio pull request #9
Opened 2023-04-19 15:52 UTC by ibugithub

- In this branch :
- We added a popup window to show the projects.

2023-04-20 16:15 UTC, Ibizugbe requested changes
Hi @ibugithub 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/233424759-4f6ea002-1bad-4e43-8a11-b5bb4e6480f4.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights✅✅

- [x] Linters are properly setup and they are passing👍.
- [x] The popup functionalities works properly👍.


## Required Changes ♻️

- [ ] Kindly ensure your popup matches the design both on mobile and on desktop😉 I suggest you make comparison with the design and make the changes where necessary as we are required to make the popup responsive and stick to the design in this milestone😉😉

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL]  Your commit messages are descriptive😉 but let's ensure they are capitalised in subsequent milestones as this is a good practice for writing professional commit messages👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 16:15 UTC, Ibizugbe commented on style.css
> +}
Nice work on your styling but we can even make it better by sticking to the given [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39-122&t=toSEotJelhIaU91X-0)😉Kindly take note of the comparison below and remember that we are to stick to the given design in this milestone and it is also a display of professionalism👍

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="300" alt="your badge" src="https://user-images.githubusercontent.com/64643995/233419392-34c0f0e7-1ba2-4e88-9ace-715b79571c5a.png">|<img width="300" alt="design" src="https://user-images.githubusercontent.com/64643995/233419254-a1c82b24-743a-4f8a-bf7c-40bcf6af8ed8.png">|


Kindly take note of the colors in the highlighted badge  and the line in the design and make the necessary change👍

2023-04-20 16:15 UTC, Ibizugbe commented on index.html
> +        <div id="project3" class="work3">
Nice job adding the popup functionality👍 Kindly note that you are required in this milestone to render the popup and project section dynamically from the array of objects you have created that contains the details about each project😉 do well to remove the project section from your `html`  file and render it dynamically with `js`👍.

<img width="824" alt="generate popup and projects section dynamically" src="https://user-images.githubusercontent.com/64643995/233424400-b0272879-76f2-4841-ac85-e653a9d7cea4.png">

2023-04-20 16:42 UTC, ibugithub commented on index.html
> +        <div id="project3" class="work3">
@Ibizugbe  Still a little confused about what I'll have to change here. Would you please explain more?

2023-04-20 17:28 UTC, Ibizugbe commented on index.html
> +        <div id="project3" class="work3">
From the requirements of [this milestone](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md), the projects or work section of your page shouold be rendered dynamically. currently, you still have your project section in your `.html` file. The instruction from the milestone requires you to take away your project section from the `.`html` file and generating it using javascript👍.

2023-04-21 12:47 UTC, andersonlebon approved these changes
## Hi @ibugithub 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 17:12 UTC, merged